CREATE TABLE IF NOT EXISTS borrowing (
                                     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
                                     borrow_date varchar(255) NULL,
                                     return_date varchar(255) NULL,
                                     book_id int8 NULL,
                                     member_id int8 NULL,
                                     CONSTRAINT borrowing_pkey PRIMARY KEY (id)
);

ALTER TABLE borrowing ADD CONSTRAINT fkpgw9do56tnua1aepwswrbwifh FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE;
ALTER TABLE borrowing ADD CONSTRAINT fkphewts11cr4frh88ht3y8ua3s FOREIGN KEY (member_id) REFERENCES member(id) ON DELETE CASCADE;